name: Playwright Tests
on:  
  pull_request:
    branches: [ master ]
jobs:
  lint:
    name: 'Lint Code'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint

  test:
    name: 'Run Tests'
    needs: lint
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL}}
    container:
      image: mcr.microsoft.com/playwright:v1.51.1-jammy
      options: --user 1001
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npx playwright test --grep "@smoke" --reporter=html
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            test-results/
            playwright-report/
      - name: Upload allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

  report:
    name: 'Generate Reports'
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results
          path: test-results/
      - name: Download allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results/
      - name: Generate Allure Report
        run: |
          npm install -g allure-commandline
          npx allure generate allure-results --clean -o allure-report
      - name: Upload HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: playwright-report/
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/
